--Select top 10 states with the highest enrollment in year 2021
SELECT SUM(ENROLLMENT) TOTAL_KIDS, FIPS
FROM EDUCATION.EDUCATION_URBAN.GRADES
WHERE YEAR = 2021
GROUP BY FIPS
ORDER BY 1 DESC
LIMIT 10;